const questions = [
  { prompt:"聽音後選出正確意思", spanish:"¿Cómo te llamas?", translation:"你叫什麼名字？", options:["你好嗎？","你叫什麼名字？","你住在哪裡？"], answer:1 },
  { prompt:"選出最自然的回答", spanish:"¿Cómo te llamas?", translation:"", options:["Me llamo Orton.","Soy de Taiwán.","Muy bien, gracias."], answer:0 },
  { prompt:"初次見面時，選出合適的說法", spanish:"Mucho gusto.", translation:"很高興認識你。", options:["Hasta mañana.","Encantado.","Buenas noches."], answer:1 },
  { prompt:"選出問題的正確回答", spanish:"¿De dónde eres?", translation:"你來自哪裡？", options:["Soy de Taiwán.","Me llamo Ana.","Hablo español."], answer:0 },
  { prompt:"完成你的迷你自我介紹", spanish:"Hola, me llamo Orton…", translation:"", options:["y soy de Taiwán.","y llamas Lucía.","y dónde eres."], answer:0 },
];
const root=document.getElementById("spanish-os");
const state={screen:"home",step:0,selected:null,score:0,combo:0,bestCombo:0,xp:120,saved:false,name:"",settings:false,confirmReset:false};
function load(){try{const p=JSON.parse(localStorage.getItem("spanish-os-progress")||"null");const u=JSON.parse(localStorage.getItem("spanish-os-profile")||"null");if(p){state.xp=p.xp??120;state.saved=!!p.completed}if(u)state.name=u.name??""}catch{localStorage.removeItem("spanish-os-progress");localStorage.removeItem("spanish-os-profile")}}
function speak(text,slow=false){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="es-ES";u.rate=slow?.68:.9;const v=speechSynthesis.getVoices().find(x=>x.lang.toLowerCase()==="es-es");if(v)u.voice=v;speechSynthesis.speak(u)}
function header(){return `<header class="topbar"><button class="brand brand-button" data-action="home"><span class="brand-mark">¡!</span><span>Spanish OS</span></button><nav class="nav-links"><button class="${state.screen==="home"?"active":""}" data-action="home">今日學習</button><button class="${state.screen==="map"?"active":""}" data-action="map">生活場景</button></nav><div class="header-actions"><div class="xp-counter"><span>XP</span><strong>${state.xp}</strong></div><button class="settings-trigger" data-action="settings" aria-label="開啟設定">${state.name?escapeHtml(state.name[0].toUpperCase()):"⚙"}</button></div></header>`}
function home(){return `<section class="hero"><div><span class="eyebrow">今日約 5 分鐘 · 西班牙西語</span><h1>Hola${state.name?`，${escapeHtml(state.name)}`:""}，今天開口<br>介紹自己吧。</h1><p>完成這堂微課程，你就能自然地告訴別人自己的名字與來自哪裡。</p><button class="primary-action" data-action="start"><span>${state.saved?"再練一次":"開始今日課程"}</span><b>→</b></button></div><div class="passport"><div class="passport-top"><span>MAD</span><i>01</i></div><div class="passport-art"><span>HOLA</span><span>¡BUENOS DÍAS!</span></div><div class="passport-copy"><small>ESCENARIO ACTUAL</small><h2>初次見面</h2><div class="route"><i class="done"></i><i class="active"></i><i></i><i></i></div><p>第 2 課，共 4 課</p></div></div></section><section class="dashboard"><article class="lesson-card"><div class="card-heading"><span class="lesson-number">02</span><div><small>今日微課程</small><h2>介紹你的名字</h2></div><span class="duration">◷ 5 分鐘</span></div><div class="lesson-preview"><button data-speak="normal" aria-label="播放發音">▶</button><div><span>¿Cómo te llamas?</span><small>你叫什麼名字？</small></div><button class="slow-audio" data-speak="slow">慢速</button></div><div class="skill-tags"><span>🔊 西班牙發音</span><span>2 個句型</span><span>5 道練習</span></div></article><aside class="ability-card"><div class="stamp ${state.saved?"earned":""}">${state.saved?"✓":"01"}<span>${state.saved?"LISTO":"EN CURSO"}</span></div><small>${state.saved?"已取得能力印章":"你已經能做到"}</small><h3>使用合適的日常問候語</h3><p>¡Hola! · Buenos días · ¿Qué tal?</p></aside></section>`}
function map(){return `<section class="map-page"><span class="eyebrow">TU RUTA · 你的學習路線</span><h1>西班牙生活能力</h1><p>每個場景約 20 分鐘，由四堂微課程組成。</p><div class="scene-path"><article class="scene-card current"><span class="scene-index">01</span><div><small>進行中 · 2 / 4</small><h2>初次見面</h2><p>問候、自我介紹，詢問姓名與來自哪裡。</p></div><button data-action="start">繼續 →</button></article><article class="scene-card"><span class="scene-index">02</span><div><small>下一站</small><h2>咖啡館與餐廳</h2><p>看懂菜單、點餐、表達需求並結帳。</p></div><span class="lock">○</span></article><article class="scene-card locked"><span class="scene-index">03</span><div><small>尚未解鎖</small><h2>交通與問路</h2><p>購票、確認班次、詢問與理解方向。</p></div><span class="lock">鎖定</span></article></div></section>`}
function lesson(){const q=questions[state.step],correct=state.selected===q.answer,progress=Math.round(((state.step+(state.selected===null?0:1))/questions.length)*100);return `<section class="lesson-screen"><div class="lesson-top"><button data-action="home" aria-label="離開課程">×</button><div class="lesson-track"><i style="width:${progress}%"></i></div><div class="combo">${state.combo>1?`🔥 ${state.combo} COMBO`:`${state.step+1} / ${questions.length}`}</div></div><div class="quiz-card"><span class="eyebrow">${q.prompt}</span><div class="sound-row"><button data-speak="normal" aria-label="播放發音">▶</button><button data-speak="slow">0.7×</button></div><h2>${q.spanish}</h2>${q.translation?`<p>${q.translation}</p>`:""}<div class="answer-grid">${q.options.map((o,i)=>`<button data-answer="${i}" ${state.selected!==null?"disabled":""} class="${state.selected===null?"":i===q.answer?"correct":i===state.selected?"wrong":"muted"}"><b>${i+1}</b>${o}</button>`).join("")}</div>${state.selected!==null?`<div class="feedback ${correct?"success":"retry"}"><div><strong>${correct?(state.combo>=2?`太棒了，${state.combo} 連擊！`:"¡Muy bien! 答對了"):"再留意這個句子的用途"}</strong><p>${correct?`+${10+Math.max(0,state.combo-1)*2} XP`:`正確答案是「${q.options[q.answer]}」`}</p></div><button data-action="next">${state.step===questions.length-1?"查看成果":"繼續 →"}</button></div>`:""}</div></section>`}
function result(){return `<section class="result-screen"><div class="confetti">◆　●　▲　◆　●</div><div class="big-stamp">✓<span>初次見面</span><small>生活能力印章</small></div><span class="eyebrow">LECCIÓN COMPLETADA</span><h1>${state.name?`${escapeHtml(state.name)}，`:""}你完成今天的任務！</h1><p>現在你能介紹自己的姓名與來自哪裡，也能聽懂對方的基本問題。</p><div class="result-stats"><div><strong>${state.score}/${questions.length}</strong><span>答對題數</span></div><div><strong>${state.bestCombo}</strong><span>最高連擊</span></div><div><strong>${state.xp}</strong><span>累積 XP</span></div></div><button class="primary-action centered" data-action="home">回到今日學習　→</button></section>`}
function settings(){return `<div class="settings-backdrop"><section class="settings-panel" role="dialog" aria-modal="true"><div class="settings-heading"><div><span class="eyebrow">PREFERENCIAS</span><h2>設定</h2></div><button data-action="close-settings" aria-label="關閉設定">×</button></div><label for="learner-name">你的名字</label><p class="field-help">用於首頁問候與課程成果，最多 30 個字。</p><input id="learner-name" maxlength="30" value="${escapeHtml(state.name)}" placeholder="例如：Orton"><button class="save-settings" data-action="save-name">儲存名字</button><div class="danger-zone"><h3>初始化學習進度</h3><p>會清除 XP、課程完成紀錄與能力印章，但保留你的名字。</p>${state.confirmReset?`<div class="reset-confirm"><span>確定要從頭開始嗎？</span><button data-action="reset">確定初始化</button><button data-action="cancel-reset">取消</button></div>`:`<button data-action="ask-reset">初始化進度</button>`}</div></section></div>`}
function escapeHtml(v){return String(v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function render(){root.innerHTML=header()+(state.screen==="home"?home():state.screen==="map"?map():state.screen==="lesson"?lesson():result())+(state.settings?settings():"");bind()}
function bind(){root.querySelectorAll("[data-action]").forEach(el=>el.onclick=()=>action(el.dataset.action));root.querySelectorAll("[data-answer]").forEach(el=>el.onclick=()=>answer(Number(el.dataset.answer)));root.querySelectorAll("[data-speak]").forEach(el=>el.onclick=()=>speak(state.screen==="lesson"?questions[state.step].spanish:"¿Cómo te llamas?",el.dataset.speak==="slow"))}
function action(a){if(a==="home"||a==="map"){state.screen=a;state.settings=false}else if(a==="start"){Object.assign(state,{screen:"lesson",step:0,selected:null,score:0,combo:0,bestCombo:0})}else if(a==="next"){if(state.step<questions.length-1){state.step++;state.selected=null}else{localStorage.setItem("spanish-os-progress",JSON.stringify({version:1,xp:state.xp,completed:true,score:state.score,date:new Date().toISOString()}));state.saved=true;state.screen="result"}}else if(a==="settings"){state.settings=true;state.confirmReset=false}else if(a==="close-settings")state.settings=false;else if(a==="save-name"){state.name=document.getElementById("learner-name").value.trim().slice(0,30);localStorage.setItem("spanish-os-profile",JSON.stringify({version:1,name:state.name}));state.settings=false}else if(a==="ask-reset")state.confirmReset=true;else if(a==="cancel-reset")state.confirmReset=false;else if(a==="reset"){localStorage.removeItem("spanish-os-progress");Object.assign(state,{xp:120,saved:false,step:0,selected:null,score:0,combo:0,bestCombo:0,screen:"home",settings:false,confirmReset:false})}render()}
function answer(i){if(state.selected!==null)return;state.selected=i;if(i===questions[state.step].answer){state.combo++;state.score++;state.bestCombo=Math.max(state.bestCombo,state.combo);state.xp+=10+Math.max(0,state.combo-1)*2}else state.combo=0;render()}
load();render();
