"use client";
import { useEffect, useMemo, useState } from "react";
type Screen = "home" | "map" | "lesson" | "result";
const questions = [
  { prompt:"聽音後選出正確意思", spanish:"¿Cómo te llamas?", translation:"你叫什麼名字？", options:["你好嗎？","你叫什麼名字？","你住在哪裡？"], answer:1 },
  { prompt:"選出最自然的回答", spanish:"¿Cómo te llamas?", translation:"", options:["Me llamo Orton.","Soy de Taiwán.","Muy bien, gracias."], answer:0 },
  { prompt:"初次見面時，選出合適的說法", spanish:"Mucho gusto.", translation:"很高興認識你。", options:["Hasta mañana.","Encantado.","Buenas noches."], answer:1 },
  { prompt:"選出問題的正確回答", spanish:"¿De dónde eres?", translation:"你來自哪裡？", options:["Soy de Taiwán.","Me llamo Ana.","Hablo español."], answer:0 },
  { prompt:"完成你的迷你自我介紹", spanish:"Hola, me llamo Orton…", translation:"", options:["y soy de Taiwán.","y llamas Lucía.","y dónde eres."], answer:0 },
];
export default function Home() {
  const [screen,setScreen]=useState<Screen>("home"), [step,setStep]=useState(0), [selected,setSelected]=useState<number|null>(null), [score,setScore]=useState(0), [combo,setCombo]=useState(0), [bestCombo,setBestCombo]=useState(0), [xp,setXp]=useState(120), [saved,setSaved]=useState(false), [name,setName]=useState(""), [draftName,setDraftName]=useState(""), [settingsOpen,setSettingsOpen]=useState(false), [confirmReset,setConfirmReset]=useState(false);
  const question=questions[step];
  const correct=selected===question.answer;
  const progress=useMemo(()=>Math.round(((step+(selected===null?0:1))/questions.length)*100),[step,selected]);
  useEffect(()=>{ try{const stored=window.localStorage.getItem("spanish-os-progress");if(stored){const value=JSON.parse(stored);setXp(value.xp??120);setSaved(Boolean(value.completed));}const profile=window.localStorage.getItem("spanish-os-profile");if(profile){const value=JSON.parse(profile);setName(value.name??"");setDraftName(value.name??"");}}catch{window.localStorage.removeItem("spanish-os-progress");window.localStorage.removeItem("spanish-os-profile");}},[]);
  function speak(text:string,slow=false){ if(!("speechSynthesis" in window))return; window.speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang="es-ES";u.rate=slow?.68:.9;const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase()==="es-es");if(voice)u.voice=voice;window.speechSynthesis.speak(u); }
  function startLesson(){setStep(0);setSelected(null);setScore(0);setCombo(0);setBestCombo(0);setScreen("lesson");}
  function choose(index:number){if(selected!==null)return;setSelected(index);if(index===question.answer){const c=combo+1;setScore(v=>v+1);setCombo(c);setBestCombo(v=>Math.max(v,c));setXp(v=>v+10+Math.max(0,c-1)*2);}else setCombo(0);}
  function next(){if(step<questions.length-1){setStep(v=>v+1);setSelected(null);}else{const result={xp,completed:true,score,date:new Date().toISOString()};window.localStorage.setItem("spanish-os-progress",JSON.stringify(result));setSaved(true);setScreen("result");}}
  function saveName(){const clean=draftName.trim().slice(0,30);setName(clean);setDraftName(clean);window.localStorage.setItem("spanish-os-profile",JSON.stringify({version:1,name:clean}));setSettingsOpen(false);}
  function resetProgress(){window.localStorage.removeItem("spanish-os-progress");window.speechSynthesis?.cancel();setXp(120);setSaved(false);setStep(0);setSelected(null);setScore(0);setCombo(0);setBestCombo(0);setScreen("home");setConfirmReset(false);setSettingsOpen(false);}
  return <main className="app-shell">
    <header className="topbar"><button className="brand brand-button" onClick={()=>setScreen("home")}><span className="brand-mark">¡!</span><span>Spanish OS</span></button><nav className="nav-links"><button className={screen==="home"?"active":""} onClick={()=>setScreen("home")}>今日學習</button><button className={screen==="map"?"active":""} onClick={()=>setScreen("map")}>生活場景</button></nav><div className="header-actions"><div className="xp-counter"><span>XP</span><strong>{xp}</strong></div><button className="settings-trigger" onClick={()=>{setDraftName(name);setConfirmReset(false);setSettingsOpen(true)}} aria-label="開啟設定">{name?name.slice(0,1).toUpperCase():"⚙"}</button></div></header>
    {screen==="home"&&<><section className="hero"><div><span className="eyebrow">今日約 5 分鐘 · 西班牙西語</span><h1>Hola{name?`，${name}`:""}，今天開口<br/>介紹自己吧。</h1><p>完成這堂微課程，你就能自然地告訴別人自己的名字與來自哪裡。</p><button className="primary-action" onClick={startLesson}><span>{saved?"再練一次":"開始今日課程"}</span><b>→</b></button></div><div className="passport"><div className="passport-top"><span>MAD</span><i>01</i></div><div className="passport-art"><span>HOLA</span><span>¡BUENOS DÍAS!</span></div><div className="passport-copy"><small>ESCENARIO ACTUAL</small><h2>初次見面</h2><div className="route"><i className="done"/><i className="active"/><i/><i/></div><p>第 2 課，共 4 課</p></div></div></section><section className="dashboard"><article className="lesson-card"><div className="card-heading"><span className="lesson-number">02</span><div><small>今日微課程</small><h2>介紹你的名字</h2></div><span className="duration">◷ 5 分鐘</span></div><div className="lesson-preview"><button onClick={()=>speak("¿Cómo te llamas?")} aria-label="播放發音">▶</button><div><span>¿Cómo te llamas?</span><small>你叫什麼名字？</small></div><button className="slow-audio" onClick={()=>speak("¿Cómo te llamas?",true)}>慢速</button></div><div className="skill-tags"><span>🔊 西班牙發音</span><span>2 個句型</span><span>5 道練習</span></div></article><aside className="ability-card"><div className={`stamp ${saved?"earned":""}`}>{saved?"✓":"01"}<span>{saved?"LISTO":"EN CURSO"}</span></div><small>{saved?"已取得能力印章":"你已經能做到"}</small><h3>使用合適的日常問候語</h3><p>¡Hola! · Buenos días · ¿Qué tal?</p></aside></section></>}
    {screen==="map"&&<section className="map-page"><span className="eyebrow">TU RUTA · 你的學習路線</span><h1>西班牙生活能力</h1><p>每個場景約 20 分鐘，由四堂微課程組成。</p><div className="scene-path"><article className="scene-card current"><span className="scene-index">01</span><div><small>進行中 · 2 / 4</small><h2>初次見面</h2><p>問候、自我介紹，詢問姓名與來自哪裡。</p></div><button onClick={startLesson}>繼續 →</button></article><article className="scene-card"><span className="scene-index">02</span><div><small>下一站</small><h2>咖啡館與餐廳</h2><p>看懂菜單、點餐、表達需求並結帳。</p></div><span className="lock">○</span></article><article className="scene-card locked"><span className="scene-index">03</span><div><small>尚未解鎖</small><h2>交通與問路</h2><p>購票、確認班次、詢問與理解方向。</p></div><span className="lock">鎖定</span></article></div></section>}
    {screen==="lesson"&&<section className="lesson-screen"><div className="lesson-top"><button onClick={()=>setScreen("home")} aria-label="離開課程">×</button><div className="lesson-track"><i style={{width:`${progress}%`}}/></div><div className="combo">{combo>1?`🔥 ${combo} COMBO`:`${step+1} / ${questions.length}`}</div></div><div className="quiz-card" key={step}><span className="eyebrow">{question.prompt}</span><div className="sound-row"><button onClick={()=>speak(question.spanish)} aria-label="播放發音">▶</button><button onClick={()=>speak(question.spanish,true)}>0.7×</button></div><h2>{question.spanish}</h2>{question.translation&&<p>{question.translation}</p>}<div className="answer-grid">{question.options.map((option,index)=><button key={option} disabled={selected!==null} onClick={()=>choose(index)} className={selected===null?"":index===question.answer?"correct":index===selected?"wrong":"muted"}><b>{index+1}</b>{option}</button>)}</div>{selected!==null&&<div className={`feedback ${correct?"success":"retry"}`}><div><strong>{correct?(combo>=2?`太棒了，${combo} 連擊！`:"¡Muy bien! 答對了"):"再留意這個句子的用途"}</strong><p>{correct?`+${10+Math.max(0,combo-1)*2} XP`:`正確答案是「${question.options[question.answer]}」`}</p></div><button onClick={next}>{step===questions.length-1?"查看成果":"繼續 →"}</button></div>}</div></section>}
    {screen==="result"&&<section className="result-screen"><div className="confetti">◆　●　▲　◆　●</div><div className="big-stamp">✓<span>初次見面</span><small>生活能力印章</small></div><span className="eyebrow">LECCIÓN COMPLETADA</span><h1>{name?`${name}，`:""}你完成今天的任務！</h1><p>現在你能介紹自己的姓名與來自哪裡，也能聽懂對方的基本問題。</p><div className="result-stats"><div><strong>{score}/{questions.length}</strong><span>答對題數</span></div><div><strong>{bestCombo}</strong><span>最高連擊</span></div><div><strong>{xp}</strong><span>累積 XP</span></div></div><button className="primary-action centered" onClick={()=>setScreen("home")}>回到今日學習　→</button></section>}
    {settingsOpen&&<div className="settings-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSettingsOpen(false)}}><section className="settings-panel" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div className="settings-heading"><div><span className="eyebrow">PREFERENCIAS</span><h2 id="settings-title">設定</h2></div><button onClick={()=>setSettingsOpen(false)} aria-label="關閉設定">×</button></div><label htmlFor="learner-name">你的名字</label><p className="field-help">用於首頁問候與課程成果，最多 30 個字。</p><input id="learner-name" value={draftName} maxLength={30} onChange={e=>setDraftName(e.target.value)} placeholder="例如：Orton" autoFocus/><button className="save-settings" onClick={saveName}>儲存名字</button><div className="danger-zone"><h3>初始化學習進度</h3><p>會清除 XP、課程完成紀錄與能力印章，但保留你的名字。</p>{!confirmReset?<button onClick={()=>setConfirmReset(true)}>初始化進度</button>:<div className="reset-confirm"><span>確定要從頭開始嗎？</span><button onClick={resetProgress}>確定初始化</button><button onClick={()=>setConfirmReset(false)}>取消</button></div>}</div></section></div>}
  </main>;
}
